-- AlterTable
ALTER TABLE "Animal" ALTER COLUMN "id" SET DEFAULT 0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "Animal_id_seq";

-- AlterTable
ALTER TABLE "Appointment" ALTER COLUMN "id" SET DEFAULT 0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "Appointment_id_seq";

-- AlterTable
ALTER TABLE "Owner" ALTER COLUMN "id" SET DEFAULT 0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "Owner_id_seq";

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT 0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "User_id_seq";
